// Lab4/eshop-ui-react/src/components/offerings/offerings.component.js
import './offerings.component.css';
import React, {Component} from "react";
import ProductBlock from "../product-block/product-block.component";
import OfferingService from "../../services/offering.service";

export default class Offerings extends Component {

    constructor(props) {
        super(props);
        this.retrieveOfferings = this.retrieveOfferings.bind(this);

        this.state = {
            offerings: []
        }
    }

    componentDidMount() {
        this.retrieveOfferings();
    }

    retrieveOfferings() {
        OfferingService.getAll()
            .then(response => {
                this.setState({
                    offerings: response.data
                });
            })
            .catch(e => {
                console.log(e);
            });
    }

    render() {
        return <div className="offerings-container">
            {
                this.state.offerings.map(function (offering) {
                    return <ProductBlock key={offering.id} dataType={'Offering'} data={offering}/>
                })
            }
        </div>
    }
}

// Lab3/eshop-ui/src/app/components/offerings/offerings.component.ts
import { Component, OnInit } from '@angular/core';
import {Offering} from '../../models/Offering';
import {OfferingService} from '../../services/offering.service';

@Component({
  selector: 'app-offerings',
  templateUrl: './offerings.component.html',
  styleUrls: ['./offerings.component.css']
})
export class OfferingsComponent implements OnInit {

  offerings: Offering[];

  constructor(private offeringService: OfferingService) {
  }

  ngOnInit(): void {
    this.loadOfferings();
  }

  private loadOfferings(): void {
    this.offeringService.getAll()
      .subscribe(offerings => this.offerings = offerings);
  }
}

<ng-container *ngFor="let offering of offerings | sort: 'name'">
  <app-product-block [data]="offering" [dataType]="'Offering'"></app-product-block>
</ng-container>
