// Lab4/eshop-ui-react/src/components/offerings/offerings.component.js
import './offerings.component.css';
import React, {Component} from "react";
import ProductBlock from "../product-block/product-block.component";
import OfferingService from "../../services/offering.service";

export default class Offerings extends Component {

    constructor(props) {
        super(props);
        this.retrieveOfferings = this.retrieveOfferings.bind(this);

        this.state = {
            offerings: []
        }
    }

    componentDidMount() {
        this.retrieveOfferings();
    }

    retrieveOfferings() {
        OfferingService.getAll()
            .then(response => {
                this.setState({
                    offerings: response.data
                });
            })
            .catch(e => {
                console.log(e);
            });
    }

    render() {
        return <div className="offerings-container">
            {
                this.state.offerings.map(function (offering) {
                    return <ProductBlock key={offering.id} dataType={'Offering'} data={offering}/>
                })
            }
        </div>
    }
}

// Lab7/eshop-ui-vue/src/components/offerings/Offerings.vue
<template>
  <div class="offerings-container" v-if="offerings">
    <ProductBlock v-for="offering in sortedOfferings" v-bind:key="offering.id"
                  v-bind:data="offering" v-bind:data-type="'Offering'"/>
    <div class="banner-container" v-if="banner">
      <img class="banner-image" v-if="banner.imageUrl" v-bind:src="banner.imageUrl" alt="Banner"/>
    </div>
  </div>
</template>

<script>
import ProductBlock from "@/components/product-block/ProductBlock";
import OfferingService from '@/services/offering.service';
import BannerService from '@/services/banner.service';
import {sortArray} from "@/utils/list-utils";

let worker;
if (window.Worker) {
  const blobURL = URL.createObjectURL(new Blob(['(',
        function () {
          self.onmessage = () => {
            /*Some hard computations here*/
            let counter = 0;
            setInterval(() => {
              if (counter++ === 1000) {
                counter = 0;
              }
              postMessage(counter);
            }, 1000);
          };
        }.toString(),
        ')()'],
      {type: 'application/javascript'}));
  worker = new Worker(blobURL);
}

export default {
  name: "Offerings",
  components: {ProductBlock},
  data() {
    return {
      banner: undefined,
      offerings: undefined
    }
  },
  created() {
    this.retrieveOfferings();
  },
  mounted() {
    if (worker) {
      worker.onmessage = (e) => {
        let counter = e.data;
        if (counter % 10 === 0) {
          this.loadBanner();
        }
      };
      worker.postMessage('');
    }
  },
  methods: {
    retrieveOfferings() {
      OfferingService.getAll()
          .then(response => {
            this.offerings = response.data;
          })
          .catch(e => {
            console.log(e);
          });
    },
    loadBanner() {
      BannerService.getRandom()
          .then(response => {
            this.banner = response.data;
          })
          .catch(e => {
            console.log(e);
          });
    }
  },
  computed: {
    sortedOfferings() {
      return sortArray(this.offerings, 'name');
    }
  }
}
</script>


<style scoped src="./Offerings.css"/>
