// Lab4/eshop-ui-react/src/components/product-item/product-item.component.js
/* eslint-disable jsx-a11y/anchor-is-valid */
import './product-item.component.css';
import {Component} from "react";
import Rating from '@material-ui/lab/Rating';
import {Button} from "@material-ui/core";
import FavoriteIcon from '@material-ui/icons/Favorite';
import ShoppingCartIcon from '@material-ui/icons/ShoppingCart';
import {GlobalContext} from "../../context-provider";
import UserService from "../../services/user.service";

export default class ProductItem extends Component {

    static contextType = GlobalContext;

    constructor(props) {
        super(props);
        this.retrieveRating = this.retrieveRating.bind(this);
        this.retrieveCommentsCount = this.retrieveCommentsCount.bind(this);
        this.onCart = this.onCart.bind(this);
        this.onWishlist = this.onWishlist.bind(this);

        this.state = {
            isInWishList: false,
            isInCart: false
        }
    }

    componentDidMount() {
        if (this.context.user) {
            this.setState({
                isInWishList: this.context.user.wishlist
                    .findIndex(product => product.id === this.props.product.id) >= 0,
                isInCart: this.context.user.cart
                    .findIndex(product => product.id === this.props.product.id) >= 0
            });
        }
    }

    retrieveRating(product) {
        if (product.ratingCount >= 1) {
            return product.ratingSum / product.ratingCount;
        }
        return 0;
    }

    retrieveCommentsCount(product) {
        const comments = product.productComments;
        return comments ? comments.length : 0;
    }

    onWishlist(e) {
        const user = this.context.user;
        if (user) {
            const index = user.wishlist.findIndex(product => product.id === this.props.product.id);
            if (index === -1) {
                user.wishlist.push(this.props.product);
                this.setState({
                    isInWishList: true
                });
            } else {
                user.wishlist.splice(index, 1);
                this.setState({
                    isInWishList: false
                });
            }
            this.context.setUser(user);
            UserService.update(user).then();
        }
    }

    onCart(e) {
        const user = this.context.user;
        if (user) {
            const index = user.cart.findIndex(product => product.id === this.props.product.id);
            if (index === -1) {
                user.cart.push(this.props.product);
                this.setState({
                    isInCart: true
                });
            } else {
                user.cart.splice(index, 1);
                this.setState({
                    isInCart: false
                });
            }
            this.context.setUser(user);
            UserService.update(user).then();
        }
    }

    render() {
        const product = this.props.product;
        return <div className="product-item">
            <div className="product-image-container">
                <img className="product-image" src={product.imageUrl} alt="Product Item"/>
            </div>
            <div className="product-info-description">
                <p className="product-name">{product.name}</p>
                <div className="product-info">
                    <div className="product-responses">
                        <div className="product-rating">
                            <Rating name="product-rating" value={this.retrieveRating(product)} precision={0.25}
                                    checkedcolor="orange" uncheckedcolor="black" size="small" readOnly={true}/>
                        </div>
                        <div className="product-comments">
                            <a href="#" className="comment">
                                <i className="fa fa-comment"/>
                                <span className="comment-value">{this.retrieveCommentsCount(product)}</span>
                            </a>
                        </div>
                    </div>
                    <div className="product-price">
                        <span className="price-value">{product.price} $</span>
                    </div>
                    <div className="product-actions">
                        <Button size="large" style={{backgroundColor: this.state.isInWishList ? 'salmon' : '#e0e0e0'}}
                                onClick={this.onWishlist}>
                            <FavoriteIcon/>
                        </Button>
                        <Button size="large" style={{backgroundColor: this.state.isInCart ? 'salmon' : '#e0e0e0'}}
                                onClick={this.onCart}>
                            <ShoppingCartIcon/>
                        </Button>
                    </div>
                </div>
            </div>
        </div>
    }
}

// Lab3/eshop-ui/src/app/components/product-item/product-item.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Product} from '../../models/Product';
import {StarRatingComponent} from 'ng-starrating';
import {ProductService} from '../../services/product.service';
import {UserService} from '../../services/user.service';

@Component({
  selector: 'app-product-item',
  templateUrl: './product-item.component.html',
  styleUrls: ['./product-item.component.css']
})
export class ProductItemComponent implements OnInit {
  @Input() product: Product;
  isInWishList: boolean;
  isInCart: boolean;

  constructor(private userService: UserService,
              private productService: ProductService) {
  }

  ngOnInit(): void {
    this.isInWishList = this.userService.userValue.wishlist
      .findIndex(product => product.id === this.product.id) >= 0;
    this.isInCart = this.userService.userValue.cart
      .findIndex(product => product.id === this.product.id) >= 0;
  }

  public retrieveRating(product: Product): number {
    if (product.ratingCount >= 1) {
      return product.ratingSum / product.ratingCount;
    }
    return 0;
  }

  public retrieveCommentsCount(product: Product): number {
    const comments = product.productComments;
    return comments ? comments.length : 0;
  }

  onRate($event: { oldValue: number; newValue: number; starRating: StarRatingComponent }): void {
    const user = this.userService.userValue;
    if (this.product.raters.findIndex(id => id === user.id) === -1) {
      this.product.ratingCount++;
      this.product.ratingSum += $event.newValue;
      this.product.raters.push(user.id);
      this.productService.update(this.product).subscribe();
    }
  }

  onWishlist($event: MouseEvent): void {
    const user = this.userService.userValue;
    const index = user.wishlist.findIndex(product => product.id === this.product.id);
    if (index === -1) {
      user.wishlist.push(this.product);
      this.isInWishList = true;
    } else {
      user.wishlist.splice(index, 1);
      this.isInWishList = false;
    }
    this.userService.update(user).subscribe();
  }

  onCart($event: MouseEvent): void {
    const user = this.userService.userValue;
    const index = user.cart.findIndex(product => product.id === this.product.id);
    if (index === -1) {
      user.cart.push(this.product);
      this.isInCart = true;
    } else {
      user.cart.splice(index, 1);
      this.isInCart = false;
    }
    this.userService.update(user).subscribe();
  }
}

<div class="product-image-container">
  <img class="product-image" src="{{product.imageUrl}}" alt="Product Item">
</div>
<div class="product-info-description">
  <p class="product-name">{{product.name}}</p>
  <div class="product-info">
    <div class="product-responses">
      <div class="product-rating">
        <star-rating value="{{retrieveRating(product)}}" [totalstars]="5" checkedcolor="orange" uncheckedcolor="black"
                     size="20px" readonly="false" (rate)="onRate($event)"></star-rating>
      </div>
      <div class="product-comments">
        <a href="#" class="comment"><i class="fa fa-comment"></i></a>
        <span class="comment-value">{{retrieveCommentsCount(product)}}</span>
      </div>
    </div>
    <div class="product-price">
      <span class="price-value">{{product.price}} $</span>
    </div>
    <div class="product-actions">
      <button [style.background-color]="isInWishList ? 'salmon' : '#e0e0e0'" mat-fab (click)="onWishlist($event)">
        <mat-icon>favorite</mat-icon>
      </button>
      <button [style.background-color]="isInCart ? 'salmon' : '#e0e0e0'" mat-fab (click)="onCart($event)">
        <mat-icon>shopping_cart</mat-icon>
      </button>
    </div>
  </div>
</div>
