// Lab4/eshop-ui-react/src/components/offerings/offerings.component.js
import './offerings.component.css';
import React, {Component} from "react";
import ProductBlock from "../product-block/product-block.component";
import OfferingService from "../../services/offering.service";

export default class Offerings extends Component {

    constructor(props) {
        super(props);
        this.retrieveOfferings = this.retrieveOfferings.bind(this);

        this.state = {
            offerings: []
        }
    }

    componentDidMount() {
        this.retrieveOfferings();
    }

    retrieveOfferings() {
        OfferingService.getAll()
            .then(response => {
                this.setState({
                    offerings: response.data
                });
            })
            .catch(e => {
                console.log(e);
            });
    }

    render() {
        return <div className="offerings-container">
            {
                this.state.offerings.map(function (offering) {
                    return <ProductBlock key={offering.id} dataType={'Offering'} data={offering}/>
                })
            }
        </div>
    }
}

// Lab5/eshop-ui-vue/src/components/offerings/Offerings.vue
<template>
  <div class="offerings-container" v-if="offerings">
    <ProductBlock v-for="offering in sortedOfferings" v-bind:key="offering.id"
                  v-bind:data="offering" v-bind:data-type="'Offering'"/>
  </div>
</template>

<script>
import ProductBlock from "@/components/product-block/ProductBlock";
import OfferingService from '@/services/offering.service';
import sortArray from "@/utils/list-utils";

export default {
  name: "Offerings",
  components: {ProductBlock},
  data() {
    return {
      offerings: undefined
    }
  },
  created() {
    this.retrieveOfferings();
  },
  methods: {
    retrieveOfferings() {
      OfferingService.getAll()
          .then(response => {
            this.offerings = response.data;
          })
          .catch(e => {
            console.log(e);
          });
    },
  },
  computed: {
    sortedOfferings() {
      return sortArray(this.offerings, 'name');
    }
  }
}
</script>

<style scoped src="./Offerings.css"/>
