// Lab3/eshop-ui/src/app/components/product-block/product-block.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {ProductCategory} from '../../models/ProductCategory';
import {Offering} from '../../models/Offering';
import {ProductService} from '../../services/product.service';
import {ProductCategoryService} from '../../services/product-category.service';
import {OfferingService} from '../../services/offering.service';
import {MatButtonToggleChange} from '@angular/material/button-toggle';
import {Product} from '../../models/Product';

@Component({
  selector: 'app-product-block',
  templateUrl: './product-block.component.html',
  styleUrls: ['./product-block.component.css']
})
export class ProductBlockComponent implements OnInit {
  @Input() data: ProductCategory | Offering;
  @Input() dataType: string;
  productCategories?: ProductCategory[];
  filteringCategories?: string[];

  constructor(private productService: ProductService,
              private offeringService: OfferingService,
              private productCategoryService: ProductCategoryService) {
  }

  ngOnInit(): void {
    this.loadProductCategories();
  }

  private loadProductCategories(): void {
    this.productCategoryService.getAll()
      .subscribe(productCategories => this.productCategories = productCategories);
  }

  getProducts(): Product[] {
    if (this.dataType === 'Offering' && this.filteringCategories && this.filteringCategories.length > 0) {
      return this.data.products.filter(product => this.filteringCategories.indexOf(product.categoryId) !== -1);
    } else {
      return this.data.products;
    }
  }

  onCategorySelectionChange($event: MatButtonToggleChange): void {
    const checked = $event.source.checked;
    const productCategory = $event.value;
    if (checked) {
      if (!this.filteringCategories) {
        this.filteringCategories = [];
      }
      this.filteringCategories.push(productCategory.id);
    } else if (this.filteringCategories.length > 0) {
      const index = this.filteringCategories.indexOf(productCategory.id);
      this.filteringCategories.splice(index, 1);
    }
  }
}

<ng-container *ngIf="data">
  <div class="product-block">
    <div *ngIf="dataType === 'Offering'">
      <h1>{{data.name}}</h1>
      <p>
        <mat-button-toggle-group multiple="true" class="product-categories" *ngIf="productCategories">
          <mat-button-toggle *ngFor="let productCategory of productCategories | sort: 'name'"
                             (change)="onCategorySelectionChange($event)"
                             [value]="productCategory" class="product-categories-item">{{productCategory.name}}</mat-button-toggle>
        </mat-button-toggle-group>
      </p>
    </div>
    <div class="product-items"
         [class.main-items]="dataType === 'Offering'"
         [class.filtered-items]="dataType === 'ProductCategory'">
      <ng-container *ngFor="let product of getProducts() | sort: 'name'">
        <app-product-item [product]="product" [class.product-item]="true"></app-product-item>
      </ng-container>
    </div>
  </div>
</ng-container>

// Lab6/eshop-ui-react/src/components/product-block/product-block.component.js
import './product-block.component.css';
import React, {Component} from "react";
import ProductCategoriesService from "../../services/product-category.service";
import ProductCategoriesButtonGroup from "./product-categories-button-group";
import ProductItem from "../product-item/product-item.component";
import sort from "../../utils/list-utils";

export default class ProductBlock extends Component {

    constructor(props) {
        super(props);
        this.retrieveProductCategories = this.retrieveProductCategories.bind(this);
        this.onFilteringCategoriesChange = this.onFilteringCategoriesChange.bind(this);
        this.getProducts = this.getProducts.bind(this);

        this.state = {
            productCategories: [],
            products: []
        }
    }

    componentDidMount() {
        this.retrieveProductCategories();
        this.setState({
            products: this.props.data ? this.props.data.products : []
        });
    }

    retrieveProductCategories() {
        ProductCategoriesService.getAll()
            .then(response => {
                this.setState({
                    productCategories: response.data
                });
            })
            .catch(e => {
                console.log(e);
            });
    }

    getProducts(filteringCategories) {
        if (filteringCategories && filteringCategories.length > 0) {
            return this.props.data.products.filter(product => filteringCategories.indexOf(product.categoryId) !== -1);
        } else {
            return this.props.data.products;
        }
    }

    onFilteringCategoriesChange(newFilteringCategories) {
        this.setState({
            products: this.getProducts(newFilteringCategories)
        });
    }

    render() {
        if (!this.props.data) return null;
        return <div className="product-block">
            {this.props.dataType === 'Offering' &&
            <div>
                <h1>{this.props.data.name}</h1>
                <div>
                    <ProductCategoriesButtonGroup parentCallback={this.onFilteringCategoriesChange}
                                                  productCategories={this.state.productCategories}/>
                </div>
            </div>
            }
            <div className={`product-items ${this.props.dataType === 'Offering' ? 'main-items' : ''} 
            ${this.props.dataType === 'ProductCategory' ? 'filtered-items' : ''}`}>
                {
                    sort(this.state.products, 'name').map(function (product) {
                        return <ProductItem key={'product-block_' + product.id} product={product}/>
                    })
                }
            </div>
        </div>
    }
}
