// Lab6/eshop-ui-react/src/components/product-item/product-item.component.js
/* eslint-disable jsx-a11y/anchor-is-valid */
import './product-item.component.css';
import {Component} from "react";
import Rating from '@material-ui/lab/Rating';
import {Button} from "@material-ui/core";
import FavoriteIcon from '@material-ui/icons/Favorite';
import ShoppingCartIcon from '@material-ui/icons/ShoppingCart';
import UserService from "../../services/user.service";
import {connect} from "react-redux";
import allActions from "../../actions";
import {observer} from "mobx-react";
import styleStore from "../store/style";
import generateColor from "../../utils/colors";

const ProductItem = observer(class ProductItem extends Component {

    constructor(props) {
        super(props);
        this.retrieveRating = this.retrieveRating.bind(this);
        this.retrieveCommentsCount = this.retrieveCommentsCount.bind(this);
        this.onCart = this.onCart.bind(this);
        this.onWishlist = this.onWishlist.bind(this);

        this.state = {
            isInWishList: false,
            isInCart: false
        }
    }

    componentDidMount() {
        if (this.props.user) {
            this.setState({
                isInWishList: this.props.user.wishlist
                    .findIndex(product => product.id === this.props.product.id) >= 0,
                isInCart: this.props.user.cart
                    .findIndex(product => product.id === this.props.product.id) >= 0
            });
        }
    }

    retrieveRating(product) {
        if (product.ratingCount >= 1) {
            return product.ratingSum / product.ratingCount;
        }
        return 0;
    }

    retrieveCommentsCount(product) {
        const comments = product.productComments;
        return comments ? comments.length : 0;
    }

    onWishlist(e) {
        const user = this.props.user;
        if (user) {
            const index = user.wishlist.findIndex(product => product.id === this.props.product.id);
            if (index === -1) {
                user.wishlist.push(this.props.product);
                this.setState({
                    isInWishList: true
                });
            } else {
                user.wishlist.splice(index, 1);
                this.setState({
                    isInWishList: false
                });
            }
            this.props.dispatch(allActions.userActions.setUser(user));
            UserService.update(user).then();
        }
    }

    onCart(e) {
        const user = this.props.user;
        if (user) {
            const index = user.cart.findIndex(product => product.id === this.props.product.id);
            if (index === -1) {
                user.cart.push(this.props.product);
                this.setState({
                    isInCart: true
                });
            } else {
                user.cart.splice(index, 1);
                this.setState({
                    isInCart: false
                });
            }
            this.props.dispatch(allActions.userActions.setUser(user));
            UserService.update(user).then();
        }
    }

    render() {
        const product = this.props.product;
        return <div className="product-item" style={{backgroundColor: !styleStore.fancy ? 'white' : generateColor()}}>
            <div className="product-image-container">
                <img className="product-image" src={product.imageUrl} alt="Product Item"/>
            </div>
            <div className="product-info-description">
                <p className="product-name">{product.name}</p>
                <div className="product-info">
                    <div className="product-responses">
                        <div className="product-rating">
                            <Rating name="product-rating" value={this.retrieveRating(product)} precision={0.25}
                                    checkedcolor="orange" uncheckedcolor="black" size="small" readOnly={true}/>
                        </div>
                        <div className="product-comments">
                            <a href="#" className="comment">
                                <i className="fa fa-comment"/>
                                <span className="comment-value">{this.retrieveCommentsCount(product)}</span>
                            </a>
                        </div>
                    </div>
                    <div className="product-price">
                        <span className="price-value">{product.price} $</span>
                    </div>
                    <div className="product-actions">
                        <Button size="large" style={{backgroundColor: this.state.isInWishList ? 'salmon' : '#e0e0e0'}}
                                onClick={this.onWishlist}>
                            <FavoriteIcon/>
                        </Button>
                        <Button size="large" style={{backgroundColor: this.state.isInCart ? 'salmon' : '#e0e0e0'}}
                                onClick={this.onCart}>
                            <ShoppingCartIcon/>
                        </Button>
                    </div>
                </div>
            </div>
        </div>
    }
});

const mapStateToProps = (state) => {
    const user = state.user;
    return {
        user
    };
}

export default connect(mapStateToProps)(ProductItem);

// Lab5/eshop-ui-vue/src/components/product-item/ProductItem.vue
<template>
  <div class="productItem">
    <div class="product-image-container">
      <img class="product-image" v-bind:src="product.imageUrl" alt="Product Item">
    </div>
    <div class="product-info-description">
      <p class="product-name">{{ product.name }}</p>
      <div class="product-info">
        <div class="product-responses">
          <div class="product-rating">
            <StarRating v-bind:value="retrieveRating(product)" v-bind:total="5" v-bind:star-size="20"/>
          </div>
          <div class="product-comments">
            <a href="#" class="comment">
              <i class="fa fa-comment"></i>
              <span class="comment-value">{{ retrieveCommentsCount(product) }}</span>
            </a>
          </div>
        </div>
        <div class="product-price">
          <span class="price-value">{{ product.price }} $</span>
        </div>
        <div class="product-actions">
          <md-button v-bind:style="{backgroundColor: isInWishlist ? 'salmon' : '#e0e0e0'}" v-on:click="onWishlist">
            <i class="fa fa-heart"/>
          </md-button>
          <md-button v-bind:style="{backgroundColor: isInCart ? 'salmon' : '#e0e0e0'}" v-on:click="onCart">
            <i class="fa fa-shopping-cart"/>
          </md-button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import StarRating from "@/components/start-rating/StarRating";
import UserService from "@/services/user.service";

export default {
  name: "ProductItem",
  components: {StarRating},
  props: ["product"],
  data() {
    return {
      isInWishlist: false,
      isInCart: false
    }
  },
  created() {
    this.isInWishlist = this.$store.state.user.wishlist
        .findIndex(product => product.id === this.product.id) >= 0;
    this.isInCart = this.$store.state.user.cart
        .findIndex(product => product.id === this.product.id) >= 0;
  },
  methods: {
    retrieveRating(product) {
      if (!product.ratingSum || !product.ratingCount) return 0;
      if (product.ratingCount >= 1) {
        return product.ratingSum / product.ratingCount;
      }
      return 0;
    },
    retrieveCommentsCount(product) {
      const comments = product.productComments;
      return comments ? comments.length : 0;
    },
    onWishlist() {
      const user = this.$store.state.user;
      console.log('user: ' + JSON.stringify(user));
      if (user) {
        const index = user.wishlist.findIndex(product => product.id === this.product.id);
        if (index === -1) {
          user.wishlist.push(this.product);
          this.isInWishlist = true;
        } else {
          user.wishlist.splice(index, 1);
          this.isInWishlist = false;
        }
        this.$store.commit('updateUser', user);
        UserService.update(user).then();
      }
    },
    onCart() {
      const user = this.$store.state.user;
      if (user) {
        const index = user.cart.findIndex(product => product.id === this.product.id);
        if (index === -1) {
          user.cart.push(this.product);
          this.isInCart = true;
        } else {
          user.cart.splice(index, 1);
          this.isInCart = false;
        }
        this.$store.commit('updateUser', user);
        UserService.update(user).then();
      }
    }
  }
}
</script>

<style scoped src="./ProductItem.css"/>
