// Lab6/eshop-ui-react/src/components/product-block/product-block.component.js
import './product-block.component.css';
import React, {Component} from "react";
import ProductCategoriesService from "../../services/product-category.service";
import ProductCategoriesButtonGroup from "./product-categories-button-group";
import ProductItem from "../product-item/product-item.component";
import sort from "../../utils/list-utils";

export default class ProductBlock extends Component {

    constructor(props) {
        super(props);
        this.retrieveProductCategories = this.retrieveProductCategories.bind(this);
        this.onFilteringCategoriesChange = this.onFilteringCategoriesChange.bind(this);
        this.getProducts = this.getProducts.bind(this);

        this.state = {
            productCategories: [],
            products: []
        }
    }

    componentDidMount() {
        this.retrieveProductCategories();
        this.setState({
            products: this.props.data ? this.props.data.products : []
        });
    }

    retrieveProductCategories() {
        ProductCategoriesService.getAll()
            .then(response => {
                this.setState({
                    productCategories: response.data
                });
            })
            .catch(e => {
                console.log(e);
            });
    }

    getProducts(filteringCategories) {
        if (filteringCategories && filteringCategories.length > 0) {
            return this.props.data.products.filter(product => filteringCategories.indexOf(product.categoryId) !== -1);
        } else {
            return this.props.data.products;
        }
    }

    onFilteringCategoriesChange(newFilteringCategories) {
        this.setState({
            products: this.getProducts(newFilteringCategories)
        });
    }

    render() {
        if (!this.props.data) return null;
        return <div className="product-block">
            {this.props.dataType === 'Offering' &&
            <div>
                <h1>{this.props.data.name}</h1>
                <div>
                    <ProductCategoriesButtonGroup parentCallback={this.onFilteringCategoriesChange}
                                                  productCategories={this.state.productCategories}/>
                </div>
            </div>
            }
            <div className={`product-items ${this.props.dataType === 'Offering' ? 'main-items' : ''} 
            ${this.props.dataType === 'ProductCategory' ? 'filtered-items' : ''}`}>
                {
                    sort(this.state.products, 'name').map(function (product) {
                        return <ProductItem key={'product-block_' + product.id} product={product}/>
                    })
                }
            </div>
        </div>
    }
}

// Lab7/eshop-ui-vue/src/components/product-block/ProductBlock.vue
<template>
  <div v-if="data" class="product-block">
    <div v-if="dataType === 'Offering'">
      <h1 class="product-block-header">{{ data.name }}</h1>
      <ul v-if="productCategories" class="product-categories">
        <li v-for="productCategory in sortedProductCategories" v-bind:key="productCategory.id">
          <md-button class="product-categories-item"
                     v-on:click="onProductCategoryItemClick(productCategory.id)"
                     v-bind:style="{backgroundColor: filteringCategories.findIndex(categoryId => categoryId === productCategory.id) >= 0 ? 'gray' : 'initial'}">
            {{ productCategory.name }}
          </md-button>
        </li>
      </ul>
    </div>
    <div class="productItems"
         v-if="products && products.length > 0"
         v-bind:class="{mainItems: dataType === 'Offering' || !dataType, filteredItems: dataType === 'ProductCategory'}">
      <ProductItem v-for="product in products" v-bind:key="product.id" v-bind:product="product"/>
    </div>
    <div class="emptyProductItems" v-else>
      <h1>Sorry, nothing found in stock by your request</h1>
      <img src="@/assets/img/empty-stock.png" alt="Empty Stock"/>
    </div>
  </div>
</template>

<script>
import ProductCategoriesService from "@/services/product-category.service";
import ProductItem from "@/components/product-item/ProductItem";
import {sortArray, groupBy} from "@/utils/list-utils";

export default {
  name: "ProductBlock",
  props: ["data", "dataType", "filteringCharacteristics"],
  components: {
    ProductItem
  },
  data() {
    return {
      productCategories: [],
      filteringCategories: []
    }
  },
  created() {
    this.retrieveProductCategories();
  },
  methods: {
    retrieveProductCategories() {
      ProductCategoriesService.getAll()
          .then(response => {
            this.productCategories = response.data;
          })
          .catch(e => {
            console.log(e);
          });
    },
    onProductCategoryItemClick(productCategoryId) {
      console.log(this.$store.state.count);
      const index = this.filteringCategories.findIndex(categoryId => categoryId === productCategoryId);
      if (index >= 0) {
        this.filteringCategories.splice(index, 1);
      } else {
        this.filteringCategories.push(productCategoryId);
      }
    }
  },
  computed: {
    sortedProductCategories() {
      return sortArray(this.productCategories, 'name');
    },
    products() {
      let productsResult = this.data.products;
      if (this.dataType === 'Offering' && this.filteringCategories && this.filteringCategories.length > 0) {
        productsResult = this.data.products.filter(product => this.filteringCategories.includes(product.categoryId));
      } else if (this.dataType === 'ProductCategory' && this.filteringCharacteristics && this.filteringCharacteristics.length > 0) {
        productsResult = productsResult.filter(product => {
          if (!product.characteristics || product.characteristics.length === 0) return false;
          const filteringCharacteristicGroups = groupBy(this.filteringCharacteristics, 'groupId');
          const productCharacteristicGroups = groupBy(product.characteristics, 'groupId');
          for (const [key, value] of Object.entries(filteringCharacteristicGroups)) {
            if (!productCharacteristicGroups[key]) return false;
            const filteringCharacteristicIds = value.map(c => c.id);
            const productCharacteristicIds = productCharacteristicGroups[key].map(c => c.id);
            if (!filteringCharacteristicIds.some(id => productCharacteristicIds.includes(id))) return false;
          }
          return true;
        });
      }
      return productsResult;
    }
  }
}
</script>

<style scoped src="./ProductBlock.css"/>
